version: 2
jobs:
  build-and-test-backend:
    docker:
      - image: holmusk/haskell-ci
    steps:
      - checkout
      - restore-cache:
          key: stack-work-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.yaml" }}
      - restore-cache:
          key: stack-global-{{ .Environment.CACHE_VERSION }}-{{ checksum "stack.yaml" }}
      - run: stack install -j1 && stack test --fast
      - save_cache:
          key: stack-global-{{ .Environment.CACHE_VERSION }}-{{ checksum "stack.yaml" }}
          paths:
            - "~/.stack"
      - save_cache:
          key: stack-work-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.yaml" }}
          paths:
            - ".stack-work"
  backend-hlint:
    docker:
      - image: holmusk/haskell-ci
    steps:
      - checkout
      - run: /root/.local/bin/hlint . -h .hlint-universum.yaml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test-backend
      - backend-hlint
