name:                three-layer
version:             0.1.0.0
github:              "githubuser/three-layer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/three-layer#readme>

dependencies:
- base-noprelude >= 4.7 && < 5
- bytestring
- mtl
- postgresql-simple
- resource-pool
- containers
- bcrypt
- servant
- servant-server
- jwt
- random
- uuid-types
- aeson
- time
- warp
- monad-logger
- ekg
- ekg-core
- universum

default-extensions:
- OverloadedStrings
- GeneralizedNewtypeDeriving
- FlexibleContexts
- RecordWildCards
- TypeApplications

library:
  source-dirs: src

executables:
  three-layer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - three-layer

tests:
  three-layer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedgehog
    - three-layer
    - tasty
    - tasty-discover
    - tasty-hspec
    - tasty-hedgehog
