name:                three-layer
version:             0.1.0.0
github:              "githubuser/three-layer"
license:             BSD3
author:              "Holmusk"
maintainer:          "example@example.com"
copyright:           "2018 Holmusk"

extra-source-files:
- README.md
- ChangeLog.md
- proto/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/three-layer#readme>

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-protoc

dependencies:
- aeson
- base-noprelude >= 4.11 && < 5
- bcrypt
- bytestring
- containers
- ekg
- ekg-core
- elm-export
- http-api-data
- jwt
- katip
- lens
- mtl
- postgresql-simple
- proto-lens
- proto-lens-protoc
- random
- relude
- resource-pool
- servant
- servant-server
- text
- time
- unordered-containers
- uuid-types
- warp

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveGeneric
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- TypeOperators

library:
  source-dirs: src
  ghc-options:
  - -Wall
  other-modules:
    - Proto.Common
    - Proto.Common_Fields
    - Proto.Login
    - Proto.Login_Fields

executables:
  three-layer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - three-layer

  generate-elm:
    main:                Main.hs
    source-dirs:         generate-elm
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - servant-elm
    - three-layer

tests:
  three-layer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hedgehog
    - three-layer
    - tasty
    - tasty-hspec
    - tasty-hedgehog
